name: Checks

on:
  pull_request:
  push:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  check:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.elm
          key: ${{ runner.os }}-${{ hashFiles('**/elm.json') }}
      - uses: cachix/install-nix-action@v21
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/fc541b860a28.tar.gz
      - uses: cachix/cachix-action@v12
        with:
          name: elm-aws-cloudfront
          authToken: ${{secrets.CACHIX_AUTH_TOKEN}}
      - name: Run tests
        run: nix-shell --run "elm-coverage"
      - name: Make build
        run: nix-shell --run "elm make --output /dev/null"